config/routes.rb
Rails.application.routes.draw do

  get 'user_details/index'

  devise_for :users
  resources :user_details

  get 'static/index'

  root 'static#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, stretches: 20
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:login]

  validates :username, uniqueness: { :case_sensitive => false }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/models/user_details.rb
class UserDetails < ActiveRecord::Base
	belongs_to :user, :foreign_key => "user_id"

	validates :fname, length: { minimum: 6 }
	validates :lname, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  #ensure_security_headers(
	#	:hsts => {:include_subdomains => true, :max_age => 20.years.to_i},
	#	:x_frame_options => 'DENY',
	#	:x_content_type_options = "nosniff",
	#	:x_xss_protection = {:value => 1, :mode => 'block'},
	#	:csp => false
	#)
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

	def index
		
	end
	
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController

  def index
  	@userdetails = UserDetails.find(current_user.id)
  end

  def edit
  	# render plain: params[:id].inspect
  	if params[:id].to_f == current_user.id
  		@userdetails = UserDetails.find(current_user.id)
  	else
  		redirect_to root_path
  	end
  end

  def update
  	@userdetails = UserDetails.find(current_user.id)
  	if @userdetails.update_attributes(detail_params)
      flash[:success] = "Profile updated"
      redirect_to @userdetails
    else
      render 'edit'
    end
  end

  def show
  	@userdetails = UserDetails.where("user_id = ?", current_user.id)
  end

  private
	def detail_params
	  params.require(:user_details).permit(:fname, :lname)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/layouts/_header.html.erb
<div class="ui pointing small inverted menu no-border">
  <%= link_to raw("<i class=\"home icon\"></i> Home"), root_path, :class => 'item' %>

  <div class="right menu">
  	<% if user_signed_in? %>
  		<div class="ui dropdown item">
			  <%= current_user.username %> <i class="icon dropdown"></i>
			  <div class="menu">
			  	<%= link_to raw("<i class=\"settings icon\"></i> Account Settings"), edit_user_registration_path, :class => 'item' %>
			    <a class="item"><i class="globe icon"></i> Choose Language</a>
			    <a class="item"><i class="edit icon"></i> Edit Profile</a>
			  </div>
			</div>
    	<%= link_to raw("<i class=\"off icon\"></i> Logout"), destroy_user_session_path, :method => 'delete', :class => 'item' %>
    <% else %>
    	<%= link_to raw("<div class=\"ui red button\"><i class=\"lock icon\"></i> Register</div>"), new_user_registration_path, :class => 'item' %>
    	<%= link_to raw("<i class=\"user icon\"></i> Sign in"), new_user_session_path, :class => 'item' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Inschef</title>
	<meta name="description" content="">
	<meta name="keyword" content="">
	<meta name="author" content="AmirolAhmad">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<%= render 'layouts/header' %>
<div class="container">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</div>

</body>
</html>

app/views/user_details/edit.html.erb
<%= form_for(@userdetails) do |f| %>
<div>
<%= f.text_field :fname %>
</div>

<div>
<%= f.text_field :lname %>
</div>

<div>
<%= f.submit "Create" %>
</div>

<% end %>

app/views/user_details/index.html.erb
<h1><%= @userdetails.fname %> <%= @userdetails.lname %></h1>

<%= link_to("Edit", edit_user_detail_path(:id => current_user.id), class: 'button') %>

app/views/user_details/show.html.erb
<h1><%= @userdetails.first.fname %> <%= @userdetails.first.lname %></h1>